package Application.Controllers;

import Application.Controllers.DTOs.FollowDTO;
import Application.Controllers.DTOs.ResponseModel;
import Application.DAOs.UserDAO;
import Application.Model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@CrossOrigin
@RestController
@RequestMapping("/User") // This means URL's start with /Usuarios (after Application path)
public class UserController {
    @Autowired // This means to get the bean called UserDAOImpl
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDAO userDAO;

    @RequestMapping(method = RequestMethod.GET)
    public Iterable<User> getAll() {
        return userDAO.findAll();
    }

    @RequestMapping(method = RequestMethod.POST)
    public ResponseEntity signup(@RequestBody User userReq) {
        if(userDAO.getByUsername(userReq.getUsername()) == null) {
            userDAO.save(userReq);
            return ResponseEntity.ok().body(userDAO.getByUsername(userReq.getUsername()));
        }
        else {
            return ResponseEntity.badRequest().build();
        }
    }

    @RequestMapping(method = RequestMethod.DELETE)
    public ResponseEntity deleteUser(@RequestParam long id) {
        userDAO.deleteById(id);
        return ResponseEntity.ok().body(new ResponseModel("Usuario eliminado."));
    }

    @RequestMapping(method = RequestMethod.PUT)
    public User updateUser(@RequestBody User user) {
        //El metodo save en una entidad con un ID ya existente, funciona como un update
        userDAO.save(user);
        return userDAO.getByUsername(user.getUsername());
    }

    @RequestMapping(value = "login", method = RequestMethod.POST)
    public ResponseEntity login(@RequestBody User userReq) {
        User userPersisted = userDAO.getByUsername(userReq.getUsername());

        if(userPersisted != null && userPersisted.getPassword().equals(userReq.getPassword())) {
            return ResponseEntity.ok().body(userPersisted);
        }
        else {
            return ResponseEntity.badRequest().body(new ResponseModel("Datos incorrectos."));
        }
    }

    @GetMapping(value = "search")
    public @ResponseBody List<User> searchByDeporte(@RequestParam String deporte) {
        return userDAO.getByDeporte(deporte);
    }

    @Transactional
    @RequestMapping(value = "follow", method = RequestMethod.POST)
    public ResponseEntity follow(@RequestBody FollowDTO followDTO) {
        User userToFollow = followDTO.toFollow;
        userToFollow.addFollower(userDAO.getByUsername(followDTO.loggedUsername));
        userDAO.save(userToFollow);

        return ResponseEntity.ok().build();
    }

}
