package Application.Controllers;

import Application.DAOs.UserDAO;
import Application.Model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/User") // This means URL's start with /Usuarios (after Application path)
public class UserController {
    @Autowired // This means to get the bean called UserDAOImpl
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDAO userDAO;

    @RequestMapping(method = RequestMethod.GET)
    public Iterable<User> getUsers() {
        return userDAO.findAll();
    }

    @RequestMapping(method = RequestMethod.POST)
    public User addUser(@RequestBody User user) {
        userDAO.save(user);
        return user;
    }

    @RequestMapping(method = RequestMethod.DELETE)
    public String deleteUser(@RequestParam long id) {
        userDAO.deleteById(id);
        return "Deleted";
    }

    @RequestMapping(method = RequestMethod.PUT)
    public String updateUser(@RequestBody User user) {
        //El metodo save en una entidad con un ID ya existente, funciona como un update
        userDAO.save(user);
        return "Updated";
    }
}
